apiVersion: v1
kind: Pod
metadata: 
  name: simple-webapp-color
  labels:
    app: webapp
spec:
  containers:
    - name: simple-webapp-color
      image: simple-webapp-color
      ports:
        - containerPort: 80
      env:
        - name: APP_COLOR
          value: pink
